# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon May 22 19:08:19 2023
# ------------------------------------------------

package:
  name: c-ares
  version: 1.19.1
source:
  sha256: 321700399b72ed0e037d0074c629e7741f6b2ec2dda92956abe3e9671d3e268e
  url: https://c-ares.haxx.se/download/c-ares-1.19.1.tar.gz
build:
  number: '0'
  run_exports:
    - c-ares >=1.19.1,<2.0a0
  string: hb547adb_0
requirements:
  build:
    - ca-certificates 2023.5.7 h8857fd0_0
    - cctools_osx-64 973.0.1 h48a5a9d_13
    - cctools_osx-arm64 973.0.1 hd9287c6_13
    - clang 15.0.7 h694c41f_2
    - clang-15 15.0.7 default_hdb78580_2
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_2
    - cmake-no-system 3.18.0 hf0c8a7f_0
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 h8ce0179_13
    - ld64_osx-arm64 609 ha71a1fd_13
    - libclang-cpp15 15.0.7 default_hdb78580_2
    - libcxx 16.0.4 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_2
    - libxml2 2.11.4 hd95e348_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 15.0.7 he4b1e75_2
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.0 h8a1eda9_3
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  run: []
  run_constraint:
    - c-ares-static <0a0
about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
