# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: openssl
  version: 3.1.2
source:
  sha256: a0ce69b8b97ea6a35b96875235aa453b966ba3cba8af2de23657d8b6767d6539
  url: http://www.openssl.org/source/openssl-3.1.2.tar.gz
build:
  no_link: lib/libcrypto.3.0.dylib
  number: 0
  run_exports:
    - openssl >=3.1.2,<4.0a0
  string: h53f4e23_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 15.0.7 h84ec8a4_3
    - make 4.3 h22f3db7_1
    - perl 5.32.1 4_h0dc2134_perl5
  run:
    - ca-certificates
  run_constrained:
    - pyopenssl >=22.1
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.1.2" openssl
  requires:
    - pkg-config
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
  home: http://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
