# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: cryptography
  version: 41.0.3
source:
  sha256: bc8427b5f09417108297b3f50b5f52f8e84ee6ebc2f073d83ffec4d39896c271
  url: https://github.com/pyca/cryptography/archive/refs/tags/41.0.3.tar.gz
build:
  number: 0
  script:
    - export OPENSSL_DIR=$PREFIX
    - python -m pip install . -vv
  string: py310hdd3b5e7_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - cffi 1.15.1 py310ha78151a_3
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - cross-python_osx-arm64 3.10 40_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libsqlite 3.42.0 h58db7d2_0
    - libxml2 2.11.4 hd95e348_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.2 h8a1eda9_0
    - popt 1.16 h7b079dc_2002
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.12 had23ca6_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - rust 1.70.0 h7e1429e_0
    - rust-std-aarch64-apple-darwin 1.70.0 hf1a8007_0
    - rust-std-x86_64-apple-darwin 1.70.0 h059895a_0
    - rust_osx-arm64 1.70.0 hcc93074_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 h829000d_7
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2023.7.22 hf0a4a13_0
    - cffi 1.15.1 py310h2399d43_3
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.42.0 hb31c410_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4 h7ea286d_0
    - openssl 3.1.2 h53f4e23_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.12 h01493a6_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h92ec313_1
    - semantic_version 2.10.0 pyhd8ed1ab_0
    - setuptools 68.0.0 pyhd8ed1ab_0
    - setuptools-rust 1.6.0 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - typing_extensions 4.7.1 pyha770c72_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.1 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - cffi >=1.12
    - openssl >=3.1.2,<4.0a0
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pytest
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors 41.0.3.*
    - hypothesis
    - iso8601
    - pretend
    - pytest
    - pytest-benchmark
    - pytest-subtests
    - pytz
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces

    to common cryptographic algorithms such as symmetric ciphers, message

    digests, and key derivation functions..

    '
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/blob/main/docs/index.rst
  doc_url: https://cryptography.io/en/latest
  home: https://cryptography.io
  license: Apache-2.0 AND BSD-3-Clause AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
  summary: cryptography is a package designed to expose cryptographic primitives and
    recipes to Python developers.
extra:
  copy_test_source_files: true
  feedstock-name: cryptography
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - ocefpaf
