# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Mar 30 14:56:35 2023
# ------------------------------------------------

package:
  name: conda
  version: 23.3.1
source:
  fn: conda-23.3.1.tar.gz
  patches:
    - patches/01-deprecations-version-fallback.patch
  sha256: f0203ae42a8a360170e8aebd45e42b6c8bf283d44b9016ef4b30451c0b55c8dc
  url: https://github.com/conda/conda/archive/23.3.1.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  string: py310hbe9552e_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 h5676edf_13
    - cctools_osx-arm64 973.0.1 he4d8a77_13
    - clang 16.0.0 h49458c0_1
    - clang-16 16.0.0 default_hd25f202_1
    - clang_osx-arm64 16.0.0 h5a16c26_0
    - clangxx 16.0.0 default_hd25f202_1
    - compiler-rt 16.0.0 h613da45_0
    - compiler-rt_osx-64 16.0.0 h613da45_0
    - cross-python_osx-arm64 3.10 40_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 hbfe4790_13
    - ld64_osx-arm64 609 h59acfe3_13
    - libclang-cpp16 16.0.0 default_hd25f202_1
    - libcxx 16.0.0 h71dddab_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.0 h7001e86_1
    - libsqlite 3.40.0 ha978bb4_0
    - libxml2 2.10.3 h554bb67_6
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 16.0.0 h7001e86_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.3 h96cf925_1
    - openssl 3.1.0 hfd90126_0
    - popt 1.16 h7b079dc_2002
    - python 3.10.10 he7542f4_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - boltons 23.0.0 pyhd8ed1ab_0
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.12.7 h4653dfc_0
    - cffi 1.15.1 py310h2399d43_3
    - colorama 0.4.6 pyhd8ed1ab_0
    - conda-package-handling 2.0.2 pyh38be061_0
    - conda-package-streaming 0.7.0 pyhd8ed1ab_1
    - libcxx 16.0.0 h75e25f2_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.40.0 h76d750c_0
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.1.0 h03a7124_0
    - packaging 23.0 pyhd8ed1ab_0
    - pip 23.0.1 pyhd8ed1ab_0
    - pluggy 1.0.0 pyhd8ed1ab_5
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.10 h3ba56d0_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h92ec313_1
    - ruamel.yaml 0.17.21 py310h8e9501a_3
    - ruamel.yaml.clib 0.2.7 py310h8e9501a_1
    - setuptools 67.6.1 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - toolz 0.12.0 pyhd8ed1ab_0
    - tqdm 4.65.0 pyhd8ed1ab_1
    - tzdata 2023c h71feb2d_0
    - wheel 0.40.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zstandard 0.19.0 py310had9512b_1
    - zstd 1.5.2 hf913c23_6
  run:
    - boltons >=23.0.0
    - conda-package-handling >=1.3.0
    - jsonpatch >=1.32
    - packaging >=23.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
    - requests >=2.20.1,<3
    - ruamel.yaml >=0.11.14,<0.18
    - setuptools >=31.0.1
    - toolz >=0.8.1
    - tqdm >=4
  run_constrained:
    - conda-build >=3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - conda-libmamba-solver >=22.12.0
    - cytoolz >=0.8.1
test:
  commands:
    - env run_pytest=no bash test_runner.sh
  downstreams:
    - conda-smithy
  files:
    - commands_to_test.sh
    - test_runner.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - responses
about:
  description: 'Conda is an open source package management system and environment
    management system for installing multiple versions of software packages and their
    dependencies and switching easily between them. It works on Linux, OS X and Windows,
    and was created for Python programs but can package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
