# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.43.0
source:
  patches: null
  sha256: 49008dbf3afc04d4edc8ecfc34e4ead196973034293c997adad2f63f01762ae1
  url: https://www.sqlite.org/2023/sqlite-autoconf-3430000.tar.gz
build:
  number: 0
  run_exports:
    - libsqlite >=3.43.0,<4.0a0
  string: hb31c410_0
requirements:
  build:
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.11.5 hd95e348_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - openssl 3.1.2 h8a1eda9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 h829000d_7
  host:
    - libzlib 1.2.13 h53f4e23_5
    - zlib 1.2.13 h53f4e23_5
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
