# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Dec 16 08:29:42 2022
# ------------------------------------------------

package:
  name: cffi
  version: 1.15.1
source:
  patches:
    - 0001-Link-to-dl-library.patch
    - 0002-setup-linux.patch
    - 0003-apple-api.patch
  sha256: d400bfb9a37b1351253cb402671cea7e89bdecc294e8016a707f6d1d8ac934f9
  url: https://pypi.io/packages/source/c/cffi/cffi-1.15.1.tar.gz
build:
  number: '3'
  script: /Users/runner/miniforge3/conda-bld/cffi_1671179893800/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: py310h2399d43_3
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - cross-python_osx-arm64 3.10 33_cpython
    - crossenv 1.2.0 pyhd8ed1ab_8
    - gettext 0.21.1 h8a4c099_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 14.0.6 hccf4f1f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm14 14.0.6 h5b596cc_1
    - libsqlite 3.40.0 ha978bb4_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.7 hfd90126_1
    - patch 2.7.6 hbcf498f_1002
    - popt 1.16 h7b079dc_2002
    - python 3.10.8 he7542f4_0_cpython
    - readline 8.1.2 h3899abd_0
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022g h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hfa58983_4
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.12.7 h4653dfc_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.40.0 h76d750c_0
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.0.7 h03a7124_1
    - pip 22.3.1 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.8 h3ba56d0_0_cpython
    - readline 8.1.2 h46ed386_0
    - setuptools 65.5.1 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - libffi >=3.4,<4.0a0
    - pycparser
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pip check
  imports:
    - _cffi_backend
    - cffi
  requires:
    - openssl
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://bitbucket.org/cffi/cffi/overview
  doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
  doc_url: http://cffi.readthedocs.org
  home: https://bitbucket.org/cffi/cffi
  license: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - katietz
    - mingwandroid
    - ocefpaf
