# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Nov  1 09:48:45 2022
# ------------------------------------------------

package:
  name: zstandard
  version: 0.19.0
source:
  sha256: 31d12fcd942dd8dbf52ca5f6b1bbe287f44e5d551a081a983ff3ea2082867863
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.19.0.tar.gz
build:
  number: '0'
  string: py310h8e9501a_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.9.24 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - cffi 1.15.1 py310ha78151a_2
    - clang 14.0.4 h694c41f_0
    - clang-14 14.0.4 default_h55ffa42_0
    - clang_osx-arm64 14.0.4 h4fe1f6c_2
    - clangxx 14.0.4 default_h55ffa42_0
    - compiler-rt 14.0.4 h7fcd477_0
    - compiler-rt_osx-64 14.0.4 h6df654d_0
    - cross-python_osx-arm64 3.10 33_cpython
    - crossenv 1.2.0 pyhd8ed1ab_8
    - gettext 0.21.1 h8a4c099_0
    - ld64_osx-64 609 h1e06c2b_10
    - ld64_osx-arm64 609 h52af8cb_10
    - libclang-cpp14 14.0.4 default_h55ffa42_0
    - libcxx 14.0.6 hccf4f1f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libsqlite 3.39.4 ha978bb4_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.4 h41df66c_0
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.5 hfd90126_2
    - popt 1.16 h7b079dc_2002
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.6 hc14f532_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1.2 h3899abd_0
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022e h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hfa58983_4
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.9.24 h4653dfc_0
    - cffi 1.15.1 py310h2399d43_2
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.39.4 h76d750c_0
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.0.5 h03a7124_2
    - pip 22.3 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.6 hae75cb6_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1.2 h46ed386_0
    - setuptools 65.5.0 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2022e h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - cffi >=1.8
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - rmax
    - xhochy
