# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Sep 28 06:13:37 2022
# ------------------------------------------------

package:
  name: yaml-cpp
  version: 0.7.0
source:
  patches:
    - fix_empty_cmake_variable.patch
    - pr_1064.patch
  sha256: 43e6a9fcb146ad871515f0d0873947e5d497a1c9c60c58cb102a97b47208b7c3
  url: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.7.0.tar.gz
build:
  number: '2'
  run_exports:
    - yaml-cpp >=0.7.0,<0.8.0a0
  string: hb7217d7_2
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2022.9.24 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 14.0.4 h694c41f_0
    - clang-14 14.0.4 default_h55ffa42_0
    - clang_osx-arm64 14.0.4 h4fe1f6c_2
    - clangxx 14.0.4 default_h55ffa42_0
    - clangxx_osx-arm64 14.0.4 h0c29b63_2
    - cmake 3.24.2 h5291bba_0
    - compiler-rt 14.0.4 h7fcd477_0
    - compiler-rt_osx-64 14.0.4 h6df654d_0
    - expat 2.4.9 hf0c8a7f_0
    - krb5 1.19.3 hb98e516_0
    - ld64_osx-64 609 h1e06c2b_10
    - ld64_osx-arm64 609 h52af8cb_10
    - libclang-cpp14 14.0.4 default_h55ffa42_0
    - libcurl 7.83.1 h23f1065_0
    - libcxx 14.0.6 hccf4f1f_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libnghttp2 1.47.0 h5aae05b_1
    - libssh2 1.10.0 h47af595_3
    - libuv 1.44.2 hac89ed1_0
    - libzlib 1.2.12 hfd90126_3
    - llvm-tools 14.0.4 h41df66c_0
    - ncurses 6.3 h96cf925_1
    - ninja 1.11.0 h1b54a9f_0
    - openssl 3.0.5 hfd90126_2
    - rhash 1.4.3 hac89ed1_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.12 hfd90126_3
    - zstd 1.5.2 hfa58983_4
  host:
    - libcxx 14.0.6 h2692d47_0
  run:
    - libcxx >=14.0.4
test:
  commands:
    - test -f $PREFIX/lib/libyaml-cpp.so
  files:
    - test
  requires:
    - clang_osx-arm64 14.*
    - clangxx_osx-arm64 14.*
    - cmake
    - ninja
about:
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp/wiki/Tutorial
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - seanyen
    - tadeu
    - wolfv
