# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Aug 28 04:29:07 2022
# ------------------------------------------------

package:
  name: fmt
  version: 9.1.0
source:
  sha256: 5dea48d1fcddc3ec571ce2058e13910a0d4a6bab4cc09a809d8b1dd1c88ae6f2
  url: https://github.com/fmtlib/fmt/archive/9.1.0.tar.gz
build:
  number: '0'
  run_exports:
    - fmt >=9.1.0,<10.0a0
  string: hffc8910_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2022.6.15 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 14.0.4 h694c41f_0
    - clang-14 14.0.4 default_h55ffa42_0
    - clang_osx-arm64 14.0.4 h4fe1f6c_2
    - clangxx 14.0.4 default_h55ffa42_0
    - clangxx_osx-arm64 14.0.4 h0c29b63_2
    - cmake 3.24.1 h5291bba_0
    - compiler-rt 14.0.4 h7fcd477_0
    - compiler-rt_osx-64 14.0.4 h6df654d_0
    - expat 2.4.8 h96cf925_0
    - krb5 1.19.3 hb98e516_0
    - ld64_osx-64 609 h1e06c2b_10
    - ld64_osx-arm64 609 h52af8cb_10
    - libclang-cpp14 14.0.4 default_h55ffa42_0
    - libcurl 7.83.1 h23f1065_0
    - libcxx 14.0.6 hce7ea42_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libnghttp2 1.47.0 h5aae05b_1
    - libssh2 1.10.0 h47af595_3
    - libuv 1.44.2 hac89ed1_0
    - libzlib 1.2.12 hfe4f2af_2
    - llvm-tools 14.0.4 h41df66c_0
    - make 4.3 h22f3db7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.5 hb81d4ab_1
    - rhash 1.4.3 hac89ed1_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.12 hfe4f2af_2
    - zstd 1.5.2 hfa58983_4
  host:
    - libcxx 14.0.6 h04bba0f_0
  run:
    - libcxx >=14.0.4
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.dylib
about:
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  dev_url: https://github.com/fmtlib/fmt
  doc_url: https://fmt.dev/latest/
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: '{fmt} is an open-source formatting library for C++'
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - saraedum
    - tdegeus
    - vitaut
