# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Aug 22 14:55:40 2023
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.24
source:
  fn: libsolv-0.7.24.tar.gz
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
  sha256: 62743265222a729c7fe94c40f7b90ccc1ac5568f5ee6df46884e7ce3c16c78c7
  url: https://github.com/openSUSE/libsolv/archive/0.7.24.tar.gz
build:
  number: '3'
  run_exports:
    - libsolv >=0.7.24,<0.8.0a0
  string: ha614eb4_3
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.19.1 h0dc2134_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - cctools_osx-arm64 973.0.1 h2f5fd4a_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-arm64 15.0.7 h1cd4f45_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-arm64 15.0.7 hc662a55_3
    - cmake 3.26.4 hf40c264_0
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - expat 2.5.0 hf0c8a7f_1
    - icu 72.1 h7336db1_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 h0fd476b_14
    - ld64_osx-arm64 609 he51b688_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcurl 8.2.1 h5f667d7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.44.2 h0dc2134_1
    - libxml2 2.11.5 hd95e348_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - make 4.3 h22f3db7_1
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.2 h8a1eda9_0
    - rhash 1.4.3 h0dc2134_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.13 h8a1eda9_5
    - zstd 1.5.2 h829000d_7
  host:
    - libcxx 16.0.6 h4653b0c_0
    - libzlib 1.2.13 h53f4e23_5
    - zlib 1.2.13 h53f4e23_5
  run:
    - libcxx >=15.0.7
    - libzlib >=1.2.13,<1.3.0a0
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - pavelzw
    - wolfv
